### ISSUE TITLE
Receiving type or Namespace name 'OptionArrayAttribute' error

### ISSUE THREAD

**Issue by ricewalker** [ALM-Rangers/Extracting-effective-permissions-from-TFS#10]
Environment:
Windows 7, VS 2015, .Net 4.5, CommandLine v2.2.1.0

I downloaded the latest build from GitHub (v1.3.0.0) and let NuGet update all the associated packages.  When I try to build I get 10 Type or Namespace name ... errors all pointing to the Options.cs file and all appearing to be because something is missing in the CommandLine dll.  I used it early last year and everything worked fine but I have had a laptop change since then and needed to download everything new.  Does anyone have any suggestions?  Any help is appreciated.

Thanks
Rick

**Comment by jeffrey-opdam** [comment]
Closing issue, due too we deprecated this project.
