### ISSUE TITLE
Error about missing nuget.exe file when it's built

### ISSUE THREAD

**Issue by Taegost** [ALM-Rangers/Extracting-effective-permissions-from-TFS#5]
When building it after downloading the nuget packages, it gives the error that it couldn't locate \.nuget\nuget.exe.
This is resolved by opening the nuget.targets file and changing the value of DownloadNuGetExe to "true".

**Comment by wpschaub** [comment]
We'd love a pull request to update the sample, so that your contribution is recorded.

**Comment by Taegost** [comment]
Thank you, I'd love to submit one but I've literally never used Git in
Visual Studio before (except to clone repositories to look at, never
committing changes).
I created a branch locally and committed the change, but if I try to
Publish or initiate a Pull Request, I get an error 403 (Forbidden).
I'm not sure if this is something I'm doing wrong, or permission settings
on the project in GitHub.

**Comment by wpschaub** [comment]
Let me confirm that you did **not** fork the repo, but created a local branch and then tried to push / create a pull request. If this is the case the process only works for members of the project. You should be forking the report and then submit a pull request. See [Fork a Repo](https://help.github.com/articles/fork-a-repo/).

**Comment by Taegost** [comment]
You are correct, it helps if I actually find a tutorial before attempting to do something I'm not familiar with :)  Pull request submitted!

**Comment by wpschaub** [comment]
Thank you for the PR. Reviewed, merged, and closed.
